#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

"""
Check_MK Checks to use with aci-ds Datasource
Place into local check-mk checks directory, e.g ~/local/share/check_mk/checks in OMD

Author:     Samuel Zehnder, zehnder@netcloud.ch
Version:    0.5

"""

def inventory_aci_health(info):
    yield None, aci_health_default_values


def check_aci_health(item, params, info):
    # health 99 3 28 34 95
    state = 0

    perfdata = []

    check, health, fcrit, fwarn, fmaj, fmin = info[0]
    msg = "Fabric Health Score: {0}".format(health)
    warn, crit = params

    if int(health) < crit:
        state = 2
        msg += "(!!)"
    elif int(health) < warn:
        msg += "(!)"
        state = 1

    msg += ", Fabric-wide Faults (crit/warn/maj/min): {0}/{1}/{2}/{3}".format(fcrit, fwarn, fmaj, fmin)

    perfdata = [
        ("health", health, warn, crit, 0, 100),
        ("fcrit", fcrit, None, None, None , None),
        ("fwarn", fwarn, None, None, None , None),
        ("fmaj", fmaj, None, None, None , None),
        ("fmin", fmin, None, None, None , None),
    ]

    return state, msg, perfdata

check_info["aci_health"] = {
    'check_function': check_aci_health,
    'inventory_function': inventory_aci_health,
    'service_description': 'Fabric Health Score',
    'has_perfdata': True,
    "includes": ["aci.include"],
}
