#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

"""
Check_MK Checks to use with aci-ds Datasource
Place into local check-mk checks directory, e.g ~/local/share/check_mk/checks in OMD

Author:     Samuel Zehnder, zehnder@netcloud.ch
Version:    0.5

"""

check_info["aci_leaf"] = {
    'check_function': check_aci_switch,
    'inventory_function': inventory_aci_node,
    'service_description': 'Leaf %s',
    'has_perfdata': True,
    "includes": ["aci.include"],
}
