#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

"""
Check_MK Checks to use with aci-ds Datasource
Place into local check-mk checks directory, e.g ~/local/share/check_mk/checks in OMD

Author:     Samuel Zehnder, zehnder@netcloud.ch
Version:    0.5

"""


def inventory_aci_controller(info):
    # controller 1 APIC1 in-service  FCH1835V2FM APIC-SERVER-M1 APIC-SERVER-M1
    for line in info:
        nnid = line[1]
        yield nnid, None


def check_aci_controller(item, params, info):
    # controller 1 APIC1 in-service  FCH1835V2FM APIC-SERVER-M1 APIC-SERVER-M1
    state = 3
    msg = 'Sorry - item not found'
    perfdata = []

    for check, nnid, name, status, serial, model, descr in info:
        if nnid == item:
            break
    else:
        return state, msg

    if status == "in-service":
        state = 0
    else:
        state = 2

    msg = '{0} is {1}, Model: {2}, Serial {3}'.format(name, status, model, serial)

    return state, msg


check_info["aci_controller"] = {
    'check_function': check_aci_controller,
    'inventory_function': inventory_aci_controller,
    'service_description': 'APIC %s',
    'has_perfdata': True,
}
