#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# This is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

"""
CMK Datasource Programm to check Cisco ACI

Authors:    Samuel Zehnder <zehnder@netcloud.ch>
            Roger Ellenberger <roger.ellenberger@wagner.ch>

"""


def agent_cisco_aci_arguments(params, hostname, ipaddress):
    """function to build command line arguments that will be used to
    invoke the special agent.
    """

    args = []
    args += ["--host", *params['host']]

    if "dns-domain" in params:
        args += ["--dns-domain", params['dns-domain']]

    args += ["--user", params['user']]
    args += ["--password", passwordstore_get_cmdline("%s", params["password"])]

    if params["only-iface-admin-up"]:
        args += ["--only-iface-admin-up"]

    skip = params.get("skip-sections")
    if skip:
        if 1 in skip:
            args += ["--skip-bgp-peer-entry"]
        if 2 in skip:
            args += ["--skip-fault-inst"]
        if 3 in skip:
            args += ["--skip-l1-phys-if"]
        if 4 in skip:
            args += ["--skip-dom-pwr-stats"]

    return args


"""register invoke function for the agent"""
special_agent_info['cisco_aci'] = agent_cisco_aci_arguments
